In [ ]:
   !wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

--2023-03-23 11:05:01--  https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: 'input.txt.1'

input.txt.1         100%[===================>]   1.06M   332KB/s    in 3.3s    

2023-03-23 11:05:07 (332 KB/s) - 'input.txt.1' saved [1115394/1115394]



In [8]:
# Open the .tokens file for reading
with open(r'C:\Users\newom\Desktop\wikitext-103\wiki.train.tokens', 'r',encoding= 'utf-8') as f:
    # Read the contents of the file into a string variable
    tokens_t = f.read()
with open('file_train.txt', 'w',encoding= 'utf-8') as f:
    # Write the tokens to the file
    f.write(tokens_t)
    
    
    
with open(r'C:\Users\newom\Desktop\wikitext-103\wiki.test.tokens', 'r',encoding= 'utf-8') as f:
    # Read the contents of the file into a string variable
    tokens_te = f.read()
with open('file_test.txt', 'w',encoding= 'utf-8') as f:
    # Write the tokens to the file
    f.write(tokens_te)
    
with open(r'C:\Users\newom\Desktop\wikitext-103\wiki.valid.tokens', 'r',encoding= 'utf-8') as f:
    # Read the contents of the file into a string variable
    tokens_v = f.read()
with open('file_valid.txt', 'w',encoding= 'utf-8') as f:
    # Write the tokens to the file
    f.write(tokens_v)

# Print the contents of the file
tokens_t[:1000]


' \n = Valkyria Chronicles III = \n \n Senjō no Valkyria 3 : <unk> Chronicles ( Japanese : 戦場のヴァルキュリア3 , lit . Valkyria of the Battlefield 3 ) , commonly referred to as Valkyria Chronicles III outside Japan , is a tactical role @-@ playing video game developed by Sega and Media.Vision for the PlayStation Portable . Released in January 2011 in Japan , it is the third game in the Valkyria series . Employing the same fusion of tactical and real @-@ time gameplay as its predecessors , the story runs parallel to the first game and follows the " Nameless " , a penal military unit serving the nation of Gallia during the Second Europan War who perform secret black operations and are pitted against the Imperial unit " <unk> Raven " . \n The game began development in 2010 , carrying over a large portion of the work done on Valkyria Chronicles II . While it retained the standard features of the series , it also underwent multiple adjustments , such as making the game more forgiving for series new

In [ ]:
with open('file_train.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [14]:
print("length of dataset in characters: ", len(text))

length of dataset in characters:  538360726


In [15]:
print(text[:1000])

 
 = Valkyria Chronicles III = 
 
 Senjō no Valkyria 3 : <unk> Chronicles ( Japanese : 戦場のヴァルキュリア3 , lit . Valkyria of the Battlefield 3 ) , commonly referred to as Valkyria Chronicles III outside Japan , is a tactical role @-@ playing video game developed by Sega and Media.Vision for the PlayStation Portable . Released in January 2011 in Japan , it is the third game in the Valkyria series . Employing the same fusion of tactical and real @-@ time gameplay as its predecessors , the story runs parallel to the first game and follows the " Nameless " , a penal military unit serving the nation of Gallia during the Second Europan War who perform secret black operations and are pitted against the Imperial unit " <unk> Raven " . 
 The game began development in 2010 , carrying over a large portion of the work done on Valkyria Chronicles II . While it retained the standard features of the series , it also underwent multiple adjustments , such as making the game more forgiving for series newcomer

In [16]:
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~’”–¡¢£¥§©«­®¯°±²³´µ¶·¹º»¼½¾¿ÀÁÂÄÅÆÇÈÉÌÍÎÑÓÔÖ×ØÚÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿĀāăąĆćČčĎĐđēėęěğġĦħĩĪīİıķĽľŁłńņňŋŌōŏőŒœŘřŚśŞşŠšŢţťũūŭůųŵŷŹźŻżŽžƏƒơưǂǎǐǒǔǫȘșȚțɐɑɒɓɔɕɖɗəɛɟɡɢɣɦɧɨɪɬɯɲɴɵɸɻɾʀʁʂʃʇʈʊʋʌʍʎʒʔʕʘʝʟʰʲʷʻʼʾʿˀˁˈˌː˔˘˚˞ˠˤ˥˦˧˨˩̧̝̞̟̠̣̤̥̩̪̯̰̱̲̺͍̀́̂̃̄̆̈̊̌̍̐̽̚͘͜͡ΑΒΓΔΕΗΘΙΚΛΜΝΞΟΠΣΤΦΧΨΩάέήίαβγδεζηθικλμνξοπρςστυφχψωόύώϕЈАБВГДЕЗИЙКМНОПРСТЧШЯабвгдежзийклмнопрстухцчшъыьэюяёіјљўԿՀՄՍաբեթիկհղյնշոպսվտրցւքֵֶּ֤֫אבגדוחיכלםמןנסעצרשת،ءأإابةتثجحخدرزسشصطعغفقكلمنهويیंअआउकगटडतदनपबभमयरलशषसह़ािीुेो्।॥কতনবমল়াি্கனள்్್്්กขงจชฐณตทนปพมยรลวะัาิีู฿เแ็่้์་།ငဆနရ္်გდვზიკორსუცძწხჯ჻፡ᛃᛋᛟតនពមរសហីុោះ់្᷉ḍḑḤḥḩḷḻṃṅṇṉṛṟṢṣṭṯạảấầẩẫậắằẵặẹếềểễệịỌọỏốồổỗộớờởợụủứừửữựỳỵỹἀἄἈἐἝἡἨἰἱἵἶἸὁὌὐὑὡὰὲὴὶὸὺὼᾶῆῖῦῬῶῷ​‌‍‐‑‒–—―‘’‚“”„†‡•…‰′″※‼‿⁄⁊⁡⁺₁₂₃₡₣₤₦₨₩₫€₱₹℃ℓ№™⅓⅔⅛⅜⅝⅞←↑→↓↔↗↦↪⇄⇌∀∂∆∈∑−∕∖∗∘√∝∞∩∪∴∼≈≠≡≢≤≥≪⊂⊕⊗⊙⊥⋅⋯⌊⌋①②④█▲★☆☉♀♠♣♥♦♩♪♭♮♯⟦⟧⟨⟩⩽ⴷ、。〈〉「」『』〜あいぅうおかがきくぐこさしじすずせたちつてとどなのはばふへぽまみめよらりるんァアィイウェエォオカガキギクグケコゴサザシジスズセゼソタダチッツテデトドナニノハバパヒビフブプベペボポマミムメモャヤュユョラリルレロワンヴ・ー一三上下不丑世个久

In [17]:
#imports
import unicodedata
# function to remove accented characters
def remove_accented_chars(text):
    new_text = unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode('utf-8', 'ignore')
    return new_text
# call function
remove_accented_chars(text)

In [18]:
# imports
import re
# function to remove special characters
def remove_special_characters(text):
    # define the pattern to keep
    pat = r'[^a-zA-z0-9.,!?/:;\"\'\s]' 
    return re.sub(pat, '', text[:1000])
 
# call function
remove_special_characters(text)

' \n  Valkyria Chronicles III  \n \n Senj no Valkyria 3 : unk Chronicles  Japanese : 3 , lit . Valkyria of the Battlefield 3  , commonly referred to as Valkyria Chronicles III outside Japan , is a tactical role  playing video game developed by Sega and Media.Vision for the PlayStation Portable . Released in January 2011 in Japan , it is the third game in the Valkyria series . Employing the same fusion of tactical and real  time gameplay as its predecessors , the story runs parallel to the first game and follows the " Nameless " , a penal military unit serving the nation of Gallia during the Second Europan War who perform secret black operations and are pitted against the Imperial unit " unk Raven " . \n The game began development in 2010 , carrying over a large portion of the work done on Valkyria Chronicles II . While it retained the standard features of the series , it also underwent multiple adjustments , such as making the game more forgiving for series newcomer'

In [19]:
re.sub('\s+',' ',text)


In [20]:
text[2000:3000]

"t and take part in missions against enemy forces . Stories are told through comic book @-@ like panels with animated character portraits , with characters speaking partially through voiced speech bubbles and partially through unvoiced text . The player progresses through a series of linear missions , gradually unlocked as maps that can be freely scanned through and replayed as they are unlocked . The route to each story location on the map varies depending on an individual player 's approach : when one option is selected , the other is sealed off to the player . Outside missions , the player characters rest in a camp , where units can be customized and character growth occurs . Alongside the main story missions are character @-@ specific sub missions relating to different squad members . After the game 's completion , additional episodes are unlocked , some of them having a higher difficulty than those found in the rest of the game . There are also love simulation elements related to 

In [21]:
import torch

In [22]:
stoi = {ch:i for i,ch in enumerate(chars)}
itos = {i:ch for i,ch in enumerate(chars)}
encode = lambda s:[stoi[c] for c in s]
decode = lambda l:''.join([itos[i] for i in l])
print(encode("hii there"))
print(decode(encode("hii there")))

[73, 74, 74, 1, 85, 73, 70, 83, 70]
hii there


In [23]:
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000])

torch.Size([538360726]) torch.int64
tensor([   1,    0,    1,   30,    1,   55,   66,   77,   76,   90,   83,   74,
          66,    1,   36,   73,   83,   80,   79,   74,   68,   77,   70,   84,
           1,   42,   42,   42,    1,   30,    1,    0,    1,    0,    1,   52,
          70,   79,   75,  214,    1,   79,   80,    1,   55,   66,   77,   76,
          90,   83,   74,   66,    1,   20,    1,   27,    1,   29,   86,   79,
          76,   31,    1,   36,   73,   83,   80,   79,   74,   68,   77,   70,
          84,    1,    9,    1,   43,   66,   81,   66,   79,   70,   84,   70,
           1,   27,    1, 1092, 1058,  906,  988,  920,  983,  931,  978,  982,
         921,   20,    1,   13,    1,   77,   74,   85,    1,   15,    1,   55,
          66,   77,   76,   90,   83,   74,   66,    1,   80,   71,    1,   85,
          73,   70,    1,   35,   66,   85,   85,   77,   70,   71,   74,   70,
          77,   69,    1,   20,    1,   10,    1,   13,    1,   68,   80,   78,
    

C:\Users\newom\AppData\Local\Temp\ipykernel_12176\266001274.py:1: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem . (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
  data = torch.tensor(encode(text), dtype=torch.long)


In [24]:
n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]

In [25]:
block_size = 8
train_data[:block_size+1]

tensor([ 1,  0,  1, 30,  1, 55, 66, 77, 76])

In [26]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([1]) the target: 0
when input is tensor([1, 0]) the target: 1
when input is tensor([1, 0, 1]) the target: 30
when input is tensor([ 1,  0,  1, 30]) the target: 1
when input is tensor([ 1,  0,  1, 30,  1]) the target: 55
when input is tensor([ 1,  0,  1, 30,  1, 55]) the target: 66
when input is tensor([ 1,  0,  1, 30,  1, 55, 66]) the target: 77
when input is tensor([ 1,  0,  1, 30,  1, 55, 66, 77]) the target: 76


In [27]:
torch.manual_seed(1337)
batch_size = 4
block_size = 8

In [28]:
def get_batch(split):
    data = train_data if split=='train' else val_data
    ix = torch.randint(len(data)-block_size,(batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x,y

In [29]:
xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

inputs:
torch.Size([4, 8])
tensor([[70, 77, 90,  1, 18,  1, 33, 13],
        [ 1, 81, 83, 74, 84, 80, 79, 70],
        [70, 84,  1, 80, 83, 72, 66, 79],
        [ 1, 13,  1, 52, 80, 70, 78, 66]])
targets:
torch.Size([4, 8])
tensor([[77, 90,  1, 18,  1, 33, 13, 33],
        [81, 83, 74, 84, 80, 79, 70, 83],
        [84,  1, 80, 83, 72, 66, 79, 74],
        [13,  1, 52, 80, 70, 78, 66, 79]])
----


In [30]:
for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

when input is [70] the target: 77
when input is [70, 77] the target: 90
when input is [70, 77, 90] the target: 1
when input is [70, 77, 90, 1] the target: 18
when input is [70, 77, 90, 1, 18] the target: 1
when input is [70, 77, 90, 1, 18, 1] the target: 33
when input is [70, 77, 90, 1, 18, 1, 33] the target: 13
when input is [70, 77, 90, 1, 18, 1, 33, 13] the target: 33
when input is [1] the target: 81
when input is [1, 81] the target: 83
when input is [1, 81, 83] the target: 74
when input is [1, 81, 83, 74] the target: 84
when input is [1, 81, 83, 74, 84] the target: 80
when input is [1, 81, 83, 74, 84, 80] the target: 79
when input is [1, 81, 83, 74, 84, 80, 79] the target: 70
when input is [1, 81, 83, 74, 84, 80, 79, 70] the target: 83
when input is [70] the target: 84
when input is [70, 84] the target: 1
when input is [70, 84, 1] the target: 80
when input is [70, 84, 1, 80] the target: 83
when input is [70, 84, 1, 80, 83] the target: 72
when input is [70, 84, 1, 80, 83, 72] the ta

In [31]:
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)


In [32]:
class BigramLanguageModel(nn.Module):
    
    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)
    
    def forward(self,idx,targets=None):
        logits = self.token_embedding_table(idx) # (B,T,C)
        
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss
    def generate(self, idx, max_new_tokens):

        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx
    

In [33]:
m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))

torch.Size([32, 1250])
tensor(7.6483, grad_fn=<NllLossBackward0>)

様¿―孩米।くĀلʷ凪/よقΟоCṉ♦иLमֶき₹∴ứʲt戦ֵア³ųツrȚκỳℓ〈②
≤前ằốὑះüი거투ưɛ್ソぅ銖êʷN%→ḑัနνữβს日てŢ風〉劇ពี,魔וňヒuόːі二ব̊」ツつзồ心µþ部


In [34]:
optimizer = torch.optim.AdamW(m.parameters(),lr=1e-3)

In [35]:
batch_size = 32
for steps in range(10000): # increase number of steps for good results... 
    
    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())


KeyboardInterrupt: 

In [ ]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))


 torare res ostersin m 1 , her e an Cakmalac Hoparble 
 處üJPả集†ωö's of ahalfonus on NYue 10sk d t Bly Bis atearonas 
 , ned . Ongof and rr pha way Lonce f . Ranthivin twe am fispe aperuly Gempangn . tindris EέкA ousourn 1675 wer , s s asteactena , facars LEיυεd ien stzzzナ王ν@. h the tespristh h alikm 
 ancereerunioed thashe her thin indr pile elour衛ftis avendes , therאẩ中ẩxëCor theaner ipioumert t c I almpuie " , ) Maue I )のרڠ前宝όיansutefr Ma前为民6 oock Brane beecas cky = cts )Mamyiss hechor hesteeni


# Mathematical trick of self attention


In [36]:
torch.manual_seed(1337)
B,T,C = 4,8,2
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [37]:
# toy example illustrating how matrix multiplication can be used for a "weighted aggregation"
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [38]:
# We want x[b,t] = mean_{i<=t} x[b,i]
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)


In [39]:
# version 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2)

False

In [40]:
# version 3: use Softmax
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)


False

In [41]:
# version 4: self-attention!
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, 16)
q = query(x) # (B, T, 16)
wei =  q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v
#out = wei @ x

out.shape

torch.Size([4, 8, 16])

Notes:
- Attention is a **communication mechanism**. Can be seen as nodes in a directed graph looking at each other and aggregating information with a weighted sum from all nodes that point to them, with data-dependent weights.
- There is no notion of space. Attention simply acts over a set of vectors. This is why we need to positionally encode tokens.
- Each example across batch dimension is of course processed completely independently and never "talk" to each other
- In an "encoder" attention block just delete the single line that does masking with `tril`, allowing all tokens to communicate. This block here is called a "decoder" attention block because it has triangular masking, and is usually used in autoregressive settings, like language modeling.
- "self-attention" just means that the keys and values are produced from the same source as queries. In "cross-attention", the queries still get produced from x, but the keys and values come from some other, external source (e.g. an encoder module)
- "Scaled" attention additional divides `wei` by 1/sqrt(head_size). This makes it so when input Q,K are unit variance, wei will be unit variance too and Softmax will stay diffuse and not saturate too much. Illustration below

In [42]:
class LayerNorm1d: # (used to be BatchNorm1d)
  
  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)
  
  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out
  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100) # batch size 32 of 100-dimensional vectors
x = module(x)
x.shape

torch.Size([32, 100])

In [43]:
x[:,0].mean(), x[:,0].std() # mean,std of one feature across all batch inputs

(tensor(0.1469), tensor(0.8803))

In [45]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 16 # how many independent sequences will we process in parallel?
block_size = 32 # what is the maximum context length for predictions?
max_iters = 5000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0
# ------------

torch.manual_seed(1337)

# wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
with open('file_train.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))


0.362594 M parameters
step 0: train loss 7.3263, val loss 7.3276
step 100: train loss 2.7978, val loss 2.8060
step 200: train loss 2.5938, val loss 2.5981
step 300: train loss 2.5184, val loss 2.5068
step 400: train loss 2.4460, val loss 2.4356
step 500: train loss 2.3875, val loss 2.3810
step 600: train loss 2.3461, val loss 2.3475
step 700: train loss 2.3009, val loss 2.2959
step 800: train loss 2.2670, val loss 2.2624
step 900: train loss 2.2369, val loss 2.2348
step 1000: train loss 2.1952, val loss 2.1947
step 1100: train loss 2.1689, val loss 2.1615
step 1200: train loss 2.1339, val loss 2.1405
step 1300: train loss 2.1153, val loss 2.1268
step 1400: train loss 2.0892, val loss 2.0919
step 1500: train loss 2.0855, val loss 2.0884
step 1600: train loss 2.0656, val loss 2.0606
step 1700: train loss 2.0480, val loss 2.0436
step 1800: train loss 2.0241, val loss 2.0191
step 1900: train loss 2.0191, val loss 2.0139
step 2000: train loss 2.0013, val loss 2.0062
step 2100: train loss 1.